### ISSUE TITLE
Make Money implement Copy

### ISSUE THREAD

**Issue by robinkrahl** [varunsrin/rusty_money#60]
`Money` has two fields, a `rust_decimal::Decimal` instance and a reference.  Both implement `Copy`, so `Money` should be able to derive `Copy`.  The [`Copy` documentation](https://doc.rust-lang.org/std/marker/trait.Copy.html#when-should-my-type-be-copy) recommends that *‘[g]enerally speaking, if your type can implement Copy, it should.’*  What do you think about making `Money` implement `Copy`?  This would make calculations much less awkward.

**Comment by brokenthorn** [comment]
Yes, this would fix having to `.clone()` money instances in cases where you need to calculate various values based off of a common value.

**Comment by FirelightFlagboy** [comment]
This issue was fixed by #82
