### ISSUE TITLE
Wrong symbol for currency RON

### ISSUE THREAD

**Issue by a-cristi** [varunsrin/rusty_money#62]
In [iso_currencies.rs](https://docs.rs/rusty-money/0.4.1/src/rusty_money/currency/iso_currencies.rs.html#1238) the `Romanian Leu` is defined as:

```rust
        RON : {
            exponent: 2,
            iso_alpha_code: "RON",
            iso_numeric_code: "946",
            locale: EnEu,
            minor_units: 1,
            name: "Romanian Leu",
            symbol: "ر.ق",
            symbol_first: false,
        },
```

The symbol should be `L` (see [the wikipedia page](https://en.wikipedia.org/wiki/Romanian_leu) for the currency).

**Comment by varunsrin** [comment]
thanks for flagging, will fix soon

**Comment by brokenthorn** [comment]
There are 2 currencies for Romania according to [ISO-4217](https://en.wikipedia.org/wiki/ISO_4217):

| Alpha Code | Numeric Code | Digits after decimal separator | Currency name | Alternative currency name |
|---|---|---|---|---|
| RON | 946 | 2 | Romanian leu | Romanian new leu |
| ROL | 642 | 0 | Romanian leu | Romanian old leu |

**Comment by brokenthorn** [comment]
@a-cristi, is this issue fixed for you now?

**Comment by a-cristi** [comment]
Yes, this is fixed now. The RON is the currently used currency, I guess you could name the ROL one as "Romanian old Leu" to distinguish between them, but I'm not sure if that is actually correct or not. 

As far as the symbols go this is now correct however. Thank you!

**Comment by brokenthorn** [comment]
> Yes, this is fixed now. The RON is the currently used currency, I guess you could name the ROL one as "Romanian old Leu" to distinguish between them, but I'm not sure if that is actually correct or not.
> 
> As far as the symbols go this is now correct however. Thank you!

I found the [ISO-4217](https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xls) current curries list. Seems RON has minor units = 2, not 1, as we have currently. I will create a new PR to fix this. The name is correct though.

![image](https://user-images.githubusercontent.com/2119004/210182868-12b559cc-40cc-49c8-991e-180efbe561b2.png)

And the [historic currencies list](https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-three.xls) also from ISO-4217, the correct name for ROL shows up as "Old Leu":

![image](https://user-images.githubusercontent.com/2119004/210182931-69806e69-9bd3-47ef-be83-61ecd08b7dea.png)

We should use the current standard name for RON and the historic currencies list name for the old ROL currency.

Does everyone agree to this?

**Comment by brokenthorn** [comment]
I need some clarification. Does `rusty_money`, in defining currencies, use `exponent` to mean the power to raise the radix (base) to, in order to get the floating point position?

And does it use `minor_units` to represent the smallest coin amount, i.e. 1 for GBP means 1 pence (1/100 of a pound sterling)?
For USD the setup is the same, only that 1 "minor_units" means 1 cent?
